language: node_js
node_js:
- 10
notifications:
  slack:
    secure: VMpXjO6/Hm+L7ExcJ7HAPOGP280vRW8n9JsUAxmxfIB9+Eh3FnjXkHrDTp8jtzPgBcB19cIl5CfJH3F7R+dngSzjb5lDGiR49JA4i3fmzxCX9EEkdLLpUuk3UqLKkZppJ1wgHbOMif93ol+Nh+aDKX20BzavV4DDDten7nLN4cizImHCZm5yCFfYZlC6DN7V6u6ICn6+WFK2eJ3+/32BIyRqF3c4j09e5DRJwj1G2Bh0ZauROXIkYH/E6yGWtk/LKWYUBBLDIkXRdFisR9by5x0xMSXMT8qbsBW0J42TERlEZvNYhL6Qn6I5U88EZCFJbuYtD4bf5U32A8iwrSeXHsIX46zhV/JCNtxI1w5iXGcAq5qPBTu9upczyfSKatt4fxX1DrTxLqhLr0xm60uCqrcHRkGXkxJptRuxw2+vDmEUb5v/ULtKhf4hsZ+53H/wt3P4m4qIz2YzA4wX4HNT6Ibsmfr+Es48ytyP82EAdpC5oYvz4iEzE+Qu1bitlA++3JcsF1QaDtTv5U7b/yO2T0ImG3Zjz0mQLtE1F/eXUpf/cW2U7HUqaNGFafKDxOs5kZMUBzHPNXmQTHxaFBoqEJPI5W+PDu8lyjfqLwQ7m9T9Ai7+k12aAq4XzV9nj+ZrBXsxeynH9N5ZWBb2ape5YRTG2N+mmV8WN7B/GOnDVg0=
